<a href="https://colab.research.google.com/github/lokkster/Full-Code-Records/blob/Code/gc_ann_to_ga_test_loop(C2_3_sum_max%2C6_crossover%2C_change_powder_mass)average_gc_1110_GBR_area_normalize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install xgboost==1.6.1
!pip install scikit-optimize


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.9/192.9 MB 5.3 MB/s eta 0:00:00
  Attempting uninstall: xgboost
    Found existing installation: xgboost 1.7.5
    Uninstalling xgboost-1.7.5:
      Successfully uninstalled xgboost-1.7.5
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.3/100.3 kB 2.1 MB/s eta 0:00:00


In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

choose between xgbr, dtr and ann (1.dtr ,2.xgbr, 3.ann)

In [ ]:
#from xgboost import XGBRegressor
#new_model=XGBRegressor()
#new_model.load_model('/content/drive/MyDrive/Colab Notebooks/xgbr_avggc5in1110.h5')

#gbr
import pickle
with open("/content/drive/MyDrive/Colab Notebooks/gbr_avggc1110areanorm.pkl" , 'rb') as f:
    new_model = pickle.load(f)


In [ ]:
#import numpy as np
#import pandas as pd
#test=np.asarray([[2,57.73,0.33,1,850]])
#pd.DataFrame(test).to_csv('test.csv')
#tests=pd.read_csv('test.csv').iloc[:,1:6].values

#print(tests)
#print(new_model.predict(tests))

In [ ]:
import pandas as pd
import numpy as np
test=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/average GC full dataset new 1110 for colab area amplified arranged for colab.csv')
Xtest=test.iloc[:,:5].values
Ytest = test.iloc[:,5:].values
print(Xtest[0])


[2.00000000e+00 4.85198001e+01 3.55247982e-01 3.00000000e+00
 1.00000000e+03]


In [ ]:
#prediction=new_model.predict(Xtest)
#print(prediction)
#print(Ytest)

#import numpy as np

#Defining MAPE function
#def MAPE(Y_actual,Y_Predicted):
 #   mape = np.mean(np.abs((Y_actual - Y_Predicted)/Y_actual))*100
  #  return mape

#LR_MAPE= MAPE(Ytest,prediction)
#print("MAPE: ",LR_MAPE)
#print(Ytest[0,2])

In [ ]:
#df=pd.DataFrame(prediction,index=None)
#arr=df[2]
#arr2=arr.to_numpy()
#print(arr2)

In [ ]:
def prediction(input):
   
   pred=new_model.predict(input)
   preddf=pd.DataFrame(pred,index=None)
   predc2h4=preddf[2]
   predacetic=preddf[3]
   predeth=preddf[4]
   predvalue=predc2h4+predacetic+predeth
   predarr=predvalue.to_numpy()

   return predarr

In [ ]:
def fitness(input):
    ans=prediction(input)
    return ans

In [ ]:
import random
#generate solutions
input=[]
for s in range(30):
    NPCtype=random.randint(1,2)
    
    NPCweight=random.randrange(27000,75000,50)/1000
    loading=random.randrange(295,495,5)/1000
    KOHconc=random.choice([1,3,0.75])
    #ratio=random.randrange(7,11,1)
    current=random.randrange(100,1001,50)


    input.append([(NPCtype,NPCweight,loading,KOHconc,current)])

input=np.asarray(input)
mating_pool=input.reshape(input.shape[0],input.shape[2])

In [ ]:
test=prediction(mating_pool)
test=np.asarray(test)

print(mating_pool)
print(test)

[[2.000e+00 6.430e+01 3.450e-01 3.000e+00 1.000e+03]
 [1.000e+00 3.310e+01 3.150e-01 3.000e+00 1.000e+02]
 [1.000e+00 6.245e+01 4.850e-01 1.000e+00 6.000e+02]
 [2.000e+00 5.270e+01 4.200e-01 3.000e+00 6.000e+02]
 [1.000e+00 6.140e+01 3.050e-01 7.500e-01 6.500e+02]
 [2.000e+00 4.425e+01 3.350e-01 7.500e-01 2.500e+02]
 [2.000e+00 4.215e+01 3.400e-01 1.000e+00 8.000e+02]
 [2.000e+00 3.810e+01 4.150e-01 1.000e+00 6.000e+02]
 [2.000e+00 4.600e+01 4.450e-01 1.000e+00 2.500e+02]
 [1.000e+00 4.235e+01 3.300e-01 1.000e+00 8.000e+02]
 [1.000e+00 6.195e+01 4.500e-01 1.000e+00 5.500e+02]
 [2.000e+00 4.665e+01 4.250e-01 1.000e+00 4.500e+02]
 [2.000e+00 4.315e+01 3.600e-01 1.000e+00 2.500e+02]
 [2.000e+00 4.060e+01 3.350e-01 7.500e-01 3.000e+02]
 [2.000e+00 4.030e+01 3.950e-01 7.500e-01 5.000e+02]
 [2.000e+00 2.755e+01 3.050e-01 1.000e+00 4.000e+02]
 [1.000e+00 6.845e+01 3.500e-01 1.000e+00 1.000e+03]
 [1.000e+00 4.985e+01 3.650e-01 3.000e+00 2.500e+02]
 [1.000e+00 5.030e+01 4.100e-01 3.000e+00 2.00

In [ ]:
#select first four as parents(best 4)
def parent_selection(mating_pool):
    fitness_mating_pool=prediction(mating_pool)
    mix_mating_fitness=np.column_stack((mating_pool,fitness_mating_pool))

    mixsort=mix_mating_fitness[mix_mating_fitness[:, 5].argsort()[::-1]]
    parents_pool=mixsort[:,0:5]
    parents_results=mixsort[:,5]
    return parents_pool

print(parent_selection(mating_pool))

[[1.000e+00 5.950e+01 4.400e-01 3.000e+00 8.000e+02]
 [2.000e+00 6.935e+01 4.900e-01 1.000e+00 6.000e+02]
 [2.000e+00 6.430e+01 3.450e-01 3.000e+00 1.000e+03]
 [1.000e+00 4.235e+01 3.300e-01 1.000e+00 8.000e+02]
 [1.000e+00 6.355e+01 3.300e-01 7.500e-01 7.000e+02]
 [2.000e+00 4.665e+01 4.250e-01 1.000e+00 4.500e+02]
 [2.000e+00 5.270e+01 4.200e-01 3.000e+00 6.000e+02]
 [2.000e+00 5.295e+01 4.250e-01 1.000e+00 4.500e+02]
 [2.000e+00 3.810e+01 4.150e-01 1.000e+00 6.000e+02]
 [2.000e+00 4.215e+01 3.400e-01 1.000e+00 8.000e+02]
 [1.000e+00 6.245e+01 4.850e-01 1.000e+00 6.000e+02]
 [1.000e+00 6.140e+01 3.050e-01 7.500e-01 6.500e+02]
 [1.000e+00 6.845e+01 3.500e-01 1.000e+00 1.000e+03]
 [1.000e+00 6.195e+01 4.500e-01 1.000e+00 5.500e+02]
 [2.000e+00 4.030e+01 3.950e-01 7.500e-01 5.000e+02]
 [2.000e+00 5.885e+01 3.550e-01 1.000e+00 6.000e+02]
 [2.000e+00 4.135e+01 3.800e-01 1.000e+00 8.500e+02]
 [2.000e+00 2.755e+01 3.050e-01 1.000e+00 4.000e+02]
 [1.000e+00 3.065e+01 3.800e-01 7.500e-01 7.00

In [ ]:
# crossover(for mating)
def uniform_crossover(A,B,C,D,E,F,P):
    for i in range(len(P)):
        if P[i]<0.5:
          temp=A[i]
          A[i]=B[i]
          B[i]=C[i]
          C[i]=D[i]
          D[i]=E[i]
          E[i]=F[i]
          F[i]=temp
    return A,B,C,D,E,F

def crossover_process(mating_pool):
    A=mating_pool[0]
    B=mating_pool[1]
    C=mating_pool[2]
    D=mating_pool[3]
    E=mating_pool[4]
    F=mating_pool[5]
    P=np.random.rand(5)
    crossover_pool=uniform_crossover(A,B,C,D,E,F,P)
    crossover_pool=np.asarray(crossover_pool)
  
    return crossover_pool






In [ ]:
#mutation!
def mutation(crossover_pool):
    mutation_rate=random.uniform(0.7,1.3)
    mutation_X=crossover_pool[:,0]
    mutation_pool=crossover_pool[:,1:]*mutation_rate
    final_mutation=np.column_stack((mutation_X,mutation_pool))
    return final_mutation

#mutation_pool=mutation(parents_pool)
#print(mutation_pool)
#print(mutation_pool)
#mutation_rate=random.uniform(0.98,1.02)
#X=mating_pool[:,0]
#mutation_pool=mating_pool[:,1:]*mutation_rate
#yui=np.column_stack((X,mutation_pool))
#print(mutation_pool,yui)

In [ ]:
#survival selection by def
def survivor_selection():
    new_mating_pool=np.insert(mutation(crossover_process(parent_selection(mating_pool))),0,mating_pool,axis=0)
    fitness_new_pool=fitness(new_mating_pool)
    mix_new_fitness=np.column_stack((new_mating_pool,fitness_new_pool))

    mixsortnew=mix_new_fitness[mix_new_fitness[:, 5].argsort()]
    mixsortnew =mixsortnew[::-1]
    mixsortnew=mixsortnew[:]
    new_mating_pool=mixsortnew[0:30,0:5]
    return new_mating_pool
    #return fitness(new_mating_pool)


test2=survivor_selection()
print(test2)

[[1.00000000e+00 5.95000000e+01 4.40000000e-01 3.00000000e+00
  8.00000000e+02]
 [2.00000000e+00 5.40997804e+01 2.69133731e-01 7.80097770e-01
  7.80097770e+02]
 [2.00000000e+00 6.93500000e+01 4.90000000e-01 1.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 6.43000000e+01 3.45000000e-01 3.00000000e+00
  1.00000000e+03]
 [2.00000000e+00 5.01602866e+01 2.57432264e-01 2.34029331e+00
  6.24078216e+02]
 [1.00000000e+00 4.23500000e+01 3.30000000e-01 1.00000000e+00
  8.00000000e+02]
 [1.00000000e+00 6.35500000e+01 3.30000000e-01 7.50000000e-01
  7.00000000e+02]
 [2.00000000e+00 4.66500000e+01 4.25000000e-01 1.00000000e+00
  4.50000000e+02]
 [2.00000000e+00 5.27000000e+01 4.20000000e-01 3.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 5.29500000e+01 4.25000000e-01 1.00000000e+00
  4.50000000e+02]
 [2.00000000e+00 3.81000000e+01 4.15000000e-01 1.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 4.21500000e+01 3.40000000e-01 1.00000000e+00
  8.00000000e+02]
 [1.00000000e+00 6.24500000e+01 4.850000

In [ ]:
def genetic_algorithm():
    parents=parent_selection(mating_pool)
    
    
    cross_p=crossover_process(parents)
   
    mutant_p=mutation(cross_p)
    survived_p=survivor_selection()
    return survived_p
    


print(genetic_algorithm())


[[1.00000000e+00 5.95000000e+01 4.40000000e-01 3.00000000e+00
  8.00000000e+02]
 [1.00000000e+00 4.93395623e+01 2.53220149e-01 2.30200135e+00
  7.67333784e+02]
 [2.00000000e+00 6.93500000e+01 4.90000000e-01 1.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 6.43000000e+01 3.45000000e-01 3.00000000e+00
  1.00000000e+03]
 [1.00000000e+00 4.23500000e+01 3.30000000e-01 1.00000000e+00
  8.00000000e+02]
 [1.00000000e+00 6.35500000e+01 3.30000000e-01 7.50000000e-01
  7.00000000e+02]
 [2.00000000e+00 4.66500000e+01 4.25000000e-01 1.00000000e+00
  4.50000000e+02]
 [2.00000000e+00 4.56563601e+01 3.75993554e-01 2.30200135e+00
  6.13867027e+02]
 [2.00000000e+00 5.27000000e+01 4.20000000e-01 3.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 5.29500000e+01 4.25000000e-01 1.00000000e+00
  4.50000000e+02]
 [2.00000000e+00 3.81000000e+01 4.15000000e-01 1.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 4.21500000e+01 3.40000000e-01 1.00000000e+00
  8.00000000e+02]
 [1.00000000e+00 6.24500000e+01 4.850000

In [ ]:
initial_gen=0
max_gen=1000

import numpy as np


while initial_gen<max_gen:
   x_new=genetic_algorithm()
   initial_gen+=1 
   mating_pool=x_new
   
   first=x_new[0]
   first=np.asarray(first)
   print([first])
   print("gen",initial_gen,"=",x_new)
   
   test=new_model.predict(x_new)
   c2test=test[:,2]+test[:,4]+test[:,3]
   print("best results:",test[0])
   
   print("Fittest C2H4+ethanol:",c2test[0])
   if c2test[0]>=70 : break
   #elif np.sum(test[0])>=97.5: break
   

[array([1.00e+00, 5.95e+01, 4.40e-01, 3.00e+00, 8.00e+02])]
gen 1 = [[1.00000000e+00 5.95000000e+01 4.40000000e-01 3.00000000e+00
  8.00000000e+02]
 [1.00000000e+00 4.52234599e+01 2.32095517e-01 2.10995925e+00
  7.03319749e+02]
 [2.00000000e+00 6.93500000e+01 4.90000000e-01 1.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 6.43000000e+01 3.45000000e-01 3.00000000e+00
  1.00000000e+03]
 [1.00000000e+00 4.23500000e+01 3.30000000e-01 1.00000000e+00
  8.00000000e+02]
 [1.00000000e+00 6.35500000e+01 3.30000000e-01 7.50000000e-01
  7.00000000e+02]
 [2.00000000e+00 4.66500000e+01 4.25000000e-01 1.00000000e+00
  4.50000000e+02]
 [2.00000000e+00 5.27000000e+01 4.20000000e-01 3.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 5.29500000e+01 4.25000000e-01 1.00000000e+00
  4.50000000e+02]
 [2.00000000e+00 3.81000000e+01 4.15000000e-01 1.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 4.21500000e+01 3.40000000e-01 1.00000000e+00
  8.00000000e+02]
 [1.00000000e+00 6.24500000e+01 4.85000000e-01 1.000

In [ ]:
print(test[0],mating_pool[0])
print(new_model.predict(mating_pool))


[15.36364731 16.44134627 50.3707038   2.56723681 20.75668746] [1.00e+00 5.95e+01 4.40e-01 3.00e+00 8.00e+02]
[[15.36364731 16.44134627 50.3707038   2.56723681 20.75668746]
 [26.29395813 12.37520868 47.12485442  0.35979629 19.2128462 ]
 [24.93070173  2.52244902 42.49019711  2.99698862 20.66625843]
 [25.53927077  7.81029912 41.49989234  4.15311581 19.77177963]
 [21.57062597 13.56324384 47.48317783  0.18223261 16.07707438]
 [16.48486011 16.58309058 48.04664705  1.43593288 13.89175076]
 [15.78292632 27.71648251 46.73419814  1.24134781 15.31698135]
 [ 9.39205065 27.69486518 36.76225478  0.94287205 20.78227096]
 [14.97055511 29.61989476 42.48743824  0.65615536 15.27875488]
 [18.48428437 22.09439101 36.47190545  2.34162916 19.40353133]
 [17.59629869 24.91442364 39.0023899   3.29321539 15.03904101]
 [19.61373011 16.97720306 36.6734666   1.70074718 18.43634199]
 [15.92659905 17.05303393 39.99893206  1.51706685 13.80321774]
 [25.49897915 11.23974838 33.74548984  2.93938153 18.49489541]
 [19.2337