In [ ]:
!pip install xgboost==1.6.1
!pip install scikit-optimize


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

choose between xgbr, dtr and ann (1.dtr ,2.xgbr, 3.ann)

In [ ]:
from xgboost import XGBRegressor
new_model=XGBRegressor()
new_model.load_model('/content/drive/MyDrive/Colab Notebooks/xgbr_avggc5in1110areanorm.h5')

#gbr
#import pickle
#with open("/content/drive/MyDrive/Colab Notebooks/gbr_avggc1110.pkl" , 'rb') as f:
#    new_model = pickle.load(f)


In [ ]:
#import numpy as np
#import pandas as pd
#test=np.asarray([[2,57.73,0.33,1,850]])
#pd.DataFrame(test).to_csv('test.csv')
#tests=pd.read_csv('test.csv').iloc[:,1:6].values

#print(tests)
#print(new_model.predict(tests))

In [ ]:
import pandas as pd
import numpy as np
test=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/average GC full dataset new 1110 for colab area amplified arranged for colab.csv')
Xtest=test.iloc[:,:5].values
Ytest = test.iloc[:,5:].values
print(Xtest[0])


[2.00000000e+00 4.85198001e+01 3.55247982e-01 3.00000000e+00
 1.00000000e+03]


In [ ]:
#prediction=new_model.predict(Xtest)
#print(prediction)
#print(Ytest)

#import numpy as np

#Defining MAPE function
#def MAPE(Y_actual,Y_Predicted):
 #   mape = np.mean(np.abs((Y_actual - Y_Predicted)/Y_actual))*100
  #  return mape

#LR_MAPE= MAPE(Ytest,prediction)
#print("MAPE: ",LR_MAPE)
#print(Ytest[0,2])

In [ ]:
#df=pd.DataFrame(prediction,index=None)
#arr=df[2]
#arr2=arr.to_numpy()
#print(arr2)

In [ ]:
def prediction(input):
   
   pred=new_model.predict(input)
   preddf=pd.DataFrame(pred,index=None)
   predc2h4=preddf[2]
   predacetic=preddf[3]
   predeth=preddf[4]
   predvalue=predc2h4+predacetic+predeth
   predarr=predvalue.to_numpy()

   return predarr

In [ ]:
def fitness(input):
    ans=prediction(input)
    return ans

In [ ]:
import random
#generate solutions
input=[]
for s in range(30):
    NPCtype=random.randint(1,2)
    
    NPCweight=random.randrange(28000,75000,50)/1000
    loading=random.randrange(295,495,5)/1000
    KOHconc=random.choice([1,3,0.75])
    #ratio=random.randrange(7,11,1)
    current=random.randrange(100,1001,50)


    input.append([(NPCtype,NPCweight,loading,KOHconc,current)])

input=np.asarray(input)
mating_pool=input.reshape(input.shape[0],input.shape[2])

In [ ]:
test=prediction(mating_pool)
test=np.asarray(test)

print(mating_pool)
print(test)

[[2.000e+00 2.865e+01 3.600e-01 1.000e+00 6.000e+02]
 [1.000e+00 6.285e+01 3.350e-01 7.500e-01 5.500e+02]
 [2.000e+00 6.600e+01 3.300e-01 3.000e+00 1.000e+02]
 [1.000e+00 3.660e+01 4.100e-01 7.500e-01 1.500e+02]
 [1.000e+00 4.515e+01 3.550e-01 3.000e+00 8.500e+02]
 [1.000e+00 5.720e+01 4.350e-01 3.000e+00 1.000e+03]
 [1.000e+00 6.020e+01 3.950e-01 7.500e-01 1.000e+03]
 [2.000e+00 4.900e+01 4.350e-01 1.000e+00 5.500e+02]
 [1.000e+00 7.045e+01 3.850e-01 3.000e+00 5.000e+02]
 [1.000e+00 5.540e+01 3.100e-01 1.000e+00 9.000e+02]
 [2.000e+00 4.615e+01 3.650e-01 7.500e-01 4.000e+02]
 [1.000e+00 2.805e+01 3.850e-01 1.000e+00 4.500e+02]
 [2.000e+00 5.730e+01 4.900e-01 1.000e+00 9.500e+02]
 [2.000e+00 3.760e+01 4.650e-01 7.500e-01 7.000e+02]
 [1.000e+00 3.455e+01 3.300e-01 7.500e-01 3.000e+02]
 [2.000e+00 3.570e+01 3.250e-01 1.000e+00 9.500e+02]
 [2.000e+00 5.250e+01 3.050e-01 3.000e+00 1.000e+03]
 [1.000e+00 5.060e+01 4.300e-01 1.000e+00 9.000e+02]
 [2.000e+00 2.810e+01 3.950e-01 3.000e+00 8.50

In [ ]:
#select first four as parents(best 4)
def parent_selection(mating_pool):
    fitness_mating_pool=prediction(mating_pool)
    mix_mating_fitness=np.column_stack((mating_pool,fitness_mating_pool))

    mixsort=mix_mating_fitness[mix_mating_fitness[:, 5].argsort()[::-1]]
    parents_pool=mixsort[:,0:5]
    parents_results=mixsort[:,5]
    return parents_pool

print(parent_selection(mating_pool))

[[1.000e+00 4.515e+01 3.550e-01 3.000e+00 8.500e+02]
 [2.000e+00 4.900e+01 4.350e-01 1.000e+00 5.500e+02]
 [1.000e+00 5.100e+01 3.350e-01 3.000e+00 1.000e+03]
 [1.000e+00 5.060e+01 4.300e-01 1.000e+00 9.000e+02]
 [1.000e+00 6.250e+01 3.400e-01 7.500e-01 7.000e+02]
 [2.000e+00 5.250e+01 3.050e-01 3.000e+00 1.000e+03]
 [1.000e+00 5.540e+01 3.100e-01 1.000e+00 9.000e+02]
 [1.000e+00 5.720e+01 4.350e-01 3.000e+00 1.000e+03]
 [2.000e+00 6.650e+01 3.800e-01 1.000e+00 1.000e+03]
 [2.000e+00 5.730e+01 4.900e-01 1.000e+00 9.500e+02]
 [2.000e+00 5.835e+01 4.050e-01 3.000e+00 1.000e+03]
 [1.000e+00 7.045e+01 3.850e-01 3.000e+00 5.000e+02]
 [1.000e+00 6.285e+01 3.350e-01 7.500e-01 5.500e+02]
 [1.000e+00 6.020e+01 3.950e-01 7.500e-01 1.000e+03]
 [2.000e+00 4.250e+01 3.650e-01 1.000e+00 7.000e+02]
 [2.000e+00 3.570e+01 3.250e-01 1.000e+00 9.500e+02]
 [2.000e+00 3.670e+01 2.950e-01 1.000e+00 8.500e+02]
 [1.000e+00 4.890e+01 3.150e-01 1.000e+00 3.500e+02]
 [1.000e+00 3.455e+01 3.300e-01 7.500e-01 3.00

In [ ]:
# crossover(for mating)
def uniform_crossover(A,B,C,D,E,F,P):
    for i in range(len(P)):
        if P[i]<0.5:
          temp=A[i]
          A[i]=B[i]
          B[i]=C[i]
          C[i]=D[i]
          D[i]=E[i]
          E[i]=F[i]
          F[i]=temp
    return A,B,C,D,E,F

def crossover_process(mating_pool):
    A=mating_pool[0]
    B=mating_pool[1]
    C=mating_pool[2]
    D=mating_pool[3]
    E=mating_pool[4]
    F=mating_pool[5]
    P=np.random.rand(5)
    crossover_pool=uniform_crossover(A,B,C,D,E,F,P)
    crossover_pool=np.asarray(crossover_pool)
  
    return crossover_pool






In [ ]:
#mutation!
def mutation(crossover_pool):
    mutation_rate=random.uniform(0.7,1.3)
    mutation_X=crossover_pool[:,0]
    mutation_pool=crossover_pool[:,1:]*mutation_rate
    final_mutation=np.column_stack((mutation_X,mutation_pool))
    return final_mutation

#mutation_pool=mutation(parents_pool)
#print(mutation_pool)
#print(mutation_pool)
#mutation_rate=random.uniform(0.98,1.02)
#X=mating_pool[:,0]
#mutation_pool=mating_pool[:,1:]*mutation_rate
#yui=np.column_stack((X,mutation_pool))
#print(mutation_pool,yui)

In [ ]:
#survival selection by def
def survivor_selection():
    new_mating_pool=np.insert(mutation(crossover_process(parent_selection(mating_pool))),0,mating_pool,axis=0)
    fitness_new_pool=fitness(new_mating_pool)
    mix_new_fitness=np.column_stack((new_mating_pool,fitness_new_pool))

    mixsortnew=mix_new_fitness[mix_new_fitness[:, 5].argsort()]
    mixsortnew =mixsortnew[::-1]
    mixsortnew=mixsortnew[:]
    new_mating_pool=mixsortnew[0:30,0:5]
    return new_mating_pool
    #return fitness(new_mating_pool)


test2=survivor_selection()
print(test2)

[[1.00000000e+00 4.51500000e+01 3.55000000e-01 3.00000000e+00
  8.50000000e+02]
 [2.00000000e+00 7.80295618e+01 3.80784262e-01 3.74541897e+00
  8.73931093e+02]
 [1.00000000e+00 6.11751765e+01 4.18238451e-01 3.74541897e+00
  6.86660144e+02]
 [1.00000000e+00 6.36721225e+01 5.36843386e-01 1.24847299e+00
  1.24847299e+03]
 [1.00000000e+00 6.31727333e+01 4.24480816e-01 9.36354742e-01
  1.12362569e+03]
 [2.00000000e+00 4.90000000e+01 4.35000000e-01 1.00000000e+00
  5.50000000e+02]
 [1.00000000e+00 5.10000000e+01 3.35000000e-01 3.00000000e+00
  1.00000000e+03]
 [1.00000000e+00 5.06000000e+01 4.30000000e-01 1.00000000e+00
  9.00000000e+02]
 [1.00000000e+00 6.25000000e+01 3.40000000e-01 7.50000000e-01
  7.00000000e+02]
 [2.00000000e+00 5.25000000e+01 3.05000000e-01 3.00000000e+00
  1.00000000e+03]
 [1.00000000e+00 6.55448320e+01 4.43207911e-01 3.74541897e+00
  1.24847299e+03]
 [1.00000000e+00 5.54000000e+01 3.10000000e-01 1.00000000e+00
  9.00000000e+02]
 [1.00000000e+00 5.72000000e+01 4.350000

In [ ]:
def genetic_algorithm():
    parents=parent_selection(mating_pool)
    
    
    cross_p=crossover_process(parents)
   
    mutant_p=mutation(cross_p)
    survived_p=survivor_selection()
    return survived_p
    


print(genetic_algorithm())


[[1.00000000e+00 4.51500000e+01 3.55000000e-01 3.00000000e+00
  8.50000000e+02]
 [2.00000000e+00 4.90000000e+01 4.35000000e-01 1.00000000e+00
  5.50000000e+02]
 [1.00000000e+00 5.10000000e+01 3.35000000e-01 3.00000000e+00
  1.00000000e+03]
 [1.00000000e+00 5.06000000e+01 4.30000000e-01 1.00000000e+00
  9.00000000e+02]
 [1.00000000e+00 6.25000000e+01 3.40000000e-01 7.50000000e-01
  7.00000000e+02]
 [2.00000000e+00 5.25000000e+01 3.05000000e-01 3.00000000e+00
  1.00000000e+03]
 [1.00000000e+00 5.54000000e+01 3.10000000e-01 1.00000000e+00
  9.00000000e+02]
 [1.00000000e+00 5.72000000e+01 4.35000000e-01 3.00000000e+00
  1.00000000e+03]
 [2.00000000e+00 6.65000000e+01 3.80000000e-01 1.00000000e+00
  1.00000000e+03]
 [2.00000000e+00 5.73000000e+01 4.90000000e-01 1.00000000e+00
  9.50000000e+02]
 [2.00000000e+00 5.83500000e+01 4.05000000e-01 3.00000000e+00
  1.00000000e+03]
 [1.00000000e+00 7.04500000e+01 3.85000000e-01 3.00000000e+00
  5.00000000e+02]
 [1.00000000e+00 6.28500000e+01 3.350000

In [ ]:
initial_gen=0
max_gen=1000

import numpy as np


while initial_gen<max_gen:
   x_new=genetic_algorithm()
   initial_gen+=1 
   mating_pool=x_new
   
   first=x_new[0]
   first=np.asarray(first)
   #print([first])
   #print("gen",initial_gen,"=",x_new)
   
   test=new_model.predict(x_new)
   c2test=test[:,2]+test[:,4]+test[:,3]
   #print("best results:",test[0])
   
   print(c2test[0])#("Fittest C2H4+ethanol:",c2test[0])
   if c2test[0]>=70 : break
   #elif np.sum(test[0])>=97.5: break

68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995
68.244995


In [ ]:
print(test[0],mating_pool[0])
print(new_model.predict(mating_pool))


[14.689836   9.704772  45.78222    2.9770234 19.48576  ] [1.00000000e+00 5.21918675e+01 3.37256516e-01 2.84083949e+00
 7.71918478e+02]
[[14.689836   9.704772  45.78222    2.9770234 19.48576  ]
 [14.689836   9.704772  45.78222    2.9770234 19.48576  ]
 [14.689836   9.704772  45.78222    2.9770234 19.48576  ]
 [14.691923   9.703988  45.218277   2.9771988 19.497314 ]
 [14.691923   9.703988  45.218277   2.9771988 19.497314 ]
 [14.691923   9.703988  45.218277   2.9771988 19.497314 ]
 [14.691923   9.703988  45.218277   2.9771988 19.497314 ]
 [14.691923   9.703988  45.218277   2.9771988 19.497314 ]
 [14.691923   9.703988  45.218277   2.9771988 19.497314 ]
 [14.691923   9.703988  45.218277   2.9771988 19.497314 ]
 [14.691923   9.703988  45.218277   2.9771988 19.497314 ]
 [14.691923   9.703988  45.218277   2.9771988 19.497314 ]
 [14.691923   9.703988  45.218277   2.9771988 19.497314 ]
 [14.691923   9.703988  45.218277   2.9771988 19.497314 ]
 [14.691923   9.703988  45.218277   2.9771988 19.4973