In [ ]:
!pip install xgboost==1.6.1
!pip install scikit-optimize


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

choose between xgbr, dtr and ann (1.dtr ,2.xgbr, 3.ann)

In [ ]:
#from xgboost import XGBRegressor
#new_model=XGBRegressor()
#new_model.load_model('/content/drive/MyDrive/Colab Notebooks/xgbr_avggc5in1110.h5')

#gbr
import pickle
with open("/content/drive/MyDrive/Colab Notebooks/rfr_avggc1110areanorm.pkl" , 'rb') as f:
    new_model = pickle.load(f)


In [ ]:
#import numpy as np
#import pandas as pd
#test=np.asarray([[2,57.73,0.33,1,850]])
#pd.DataFrame(test).to_csv('test.csv')
#tests=pd.read_csv('test.csv').iloc[:,1:6].values

#print(tests)
#print(new_model.predict(tests))

In [ ]:
import pandas as pd
import numpy as np
test=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/average GC full dataset new 1110 for colab area amplified arranged for colab.csv')
Xtest=test.iloc[:,:5].values
Ytest = test.iloc[:,5:].values
print(Xtest[0])


[2.00000000e+00 4.85198001e+01 3.55247982e-01 3.00000000e+00
 1.00000000e+03]


In [ ]:
#prediction=new_model.predict(Xtest)
#print(prediction)
#print(Ytest)

#import numpy as np

#Defining MAPE function
#def MAPE(Y_actual,Y_Predicted):
 #   mape = np.mean(np.abs((Y_actual - Y_Predicted)/Y_actual))*100
  #  return mape

#LR_MAPE= MAPE(Ytest,prediction)
#print("MAPE: ",LR_MAPE)
#print(Ytest[0,2])

In [ ]:
#df=pd.DataFrame(prediction,index=None)
#arr=df[2]
#arr2=arr.to_numpy()
#print(arr2)

In [ ]:
def prediction(input):
   
   pred=new_model.predict(input)
   preddf=pd.DataFrame(pred,index=None)
   predc2h4=preddf[2]
   predacetic=preddf[3]
   predeth=preddf[4]
   predvalue=predc2h4+predacetic+predeth
   predarr=predvalue.to_numpy()

   return predarr

In [ ]:
def fitness(input):
    ans=prediction(input)
    return ans

In [ ]:
import random
#generate solutions
input=[]
for s in range(30):
    NPCtype=random.randint(1,2)
    
    NPCweight=random.randrange(28000,75000,50)/1000
    loading=random.randrange(295,495,5)/1000
    KOHconc=random.choice([1,3,0.75])
    #ratio=random.randrange(7,11,1)
    current=random.randrange(100,1001,50)


    input.append([(NPCtype,NPCweight,loading,KOHconc,current)])

input=np.asarray(input)
mating_pool=input.reshape(input.shape[0],input.shape[2])

In [ ]:
test=prediction(mating_pool)
test=np.asarray(test)

print(mating_pool)
print(test)

[[2.000e+00 3.460e+01 3.700e-01 1.000e+00 2.500e+02]
 [2.000e+00 4.480e+01 4.250e-01 1.000e+00 9.000e+02]
 [2.000e+00 3.500e+01 3.250e-01 1.000e+00 9.500e+02]
 [1.000e+00 4.310e+01 4.700e-01 1.000e+00 5.500e+02]
 [1.000e+00 4.460e+01 3.650e-01 1.000e+00 2.000e+02]
 [1.000e+00 4.415e+01 4.500e-01 7.500e-01 1.500e+02]
 [2.000e+00 5.675e+01 4.650e-01 7.500e-01 3.000e+02]
 [2.000e+00 5.195e+01 4.100e-01 3.000e+00 3.000e+02]
 [2.000e+00 7.245e+01 3.200e-01 7.500e-01 2.500e+02]
 [1.000e+00 6.095e+01 3.000e-01 7.500e-01 1.500e+02]
 [2.000e+00 3.280e+01 4.050e-01 3.000e+00 5.000e+02]
 [2.000e+00 7.410e+01 3.750e-01 3.000e+00 9.500e+02]
 [1.000e+00 4.100e+01 4.800e-01 3.000e+00 8.000e+02]
 [1.000e+00 4.525e+01 3.100e-01 1.000e+00 7.000e+02]
 [1.000e+00 6.630e+01 3.800e-01 3.000e+00 1.500e+02]
 [2.000e+00 6.390e+01 4.400e-01 7.500e-01 6.500e+02]
 [2.000e+00 6.040e+01 3.800e-01 3.000e+00 7.500e+02]
 [1.000e+00 3.160e+01 4.000e-01 3.000e+00 8.500e+02]
 [1.000e+00 7.390e+01 4.750e-01 1.000e+00 3.50

In [ ]:
#select first four as parents(best 4)
def parent_selection(mating_pool):
    fitness_mating_pool=prediction(mating_pool)
    mix_mating_fitness=np.column_stack((mating_pool,fitness_mating_pool))

    mixsort=mix_mating_fitness[mix_mating_fitness[:, 5].argsort()[::-1]]
    parents_pool=mixsort[:,0:5]
    parents_results=mixsort[:,5]
    return parents_pool

print(parent_selection(mating_pool))

[[2.000e+00 7.310e+01 4.150e-01 1.000e+00 6.000e+02]
 [2.000e+00 6.785e+01 3.150e-01 3.000e+00 9.500e+02]
 [1.000e+00 6.605e+01 4.850e-01 3.000e+00 6.000e+02]
 [2.000e+00 6.040e+01 3.800e-01 3.000e+00 7.500e+02]
 [2.000e+00 4.480e+01 4.250e-01 1.000e+00 9.000e+02]
 [2.000e+00 6.390e+01 4.400e-01 7.500e-01 6.500e+02]
 [2.000e+00 7.410e+01 3.750e-01 3.000e+00 9.500e+02]
 [2.000e+00 6.820e+01 3.750e-01 7.500e-01 6.000e+02]
 [2.000e+00 3.500e+01 3.250e-01 1.000e+00 9.500e+02]
 [1.000e+00 4.525e+01 3.100e-01 1.000e+00 7.000e+02]
 [1.000e+00 3.160e+01 4.000e-01 3.000e+00 8.500e+02]
 [2.000e+00 6.245e+01 4.750e-01 3.000e+00 4.500e+02]
 [1.000e+00 4.310e+01 4.700e-01 1.000e+00 5.500e+02]
 [1.000e+00 4.100e+01 4.800e-01 3.000e+00 8.000e+02]
 [2.000e+00 3.805e+01 2.950e-01 1.000e+00 6.000e+02]
 [1.000e+00 7.390e+01 4.750e-01 1.000e+00 3.500e+02]
 [2.000e+00 3.280e+01 4.050e-01 3.000e+00 5.000e+02]
 [1.000e+00 3.200e+01 4.400e-01 3.000e+00 9.000e+02]
 [2.000e+00 4.055e+01 3.300e-01 1.000e+00 4.00

In [ ]:
# crossover(for mating)
def uniform_crossover(A,B,C,D,E,F,P):
    for i in range(len(P)):
        if P[i]<0.5:
          temp=A[i]
          A[i]=B[i]
          B[i]=C[i]
          C[i]=D[i]
          D[i]=E[i]
          E[i]=F[i]
          F[i]=temp
    return A,B,C,D,E,F

def crossover_process(mating_pool):
    A=mating_pool[0]
    B=mating_pool[1]
    C=mating_pool[2]
    D=mating_pool[3]
    E=mating_pool[4]
    F=mating_pool[5]
    P=np.random.rand(5)
    crossover_pool=uniform_crossover(A,B,C,D,E,F,P)
    crossover_pool=np.asarray(crossover_pool)
  
    return crossover_pool






In [ ]:
#mutation!
def mutation(crossover_pool):
    mutation_rate=random.uniform(0.7,1.3)
    mutation_X=crossover_pool[:,0]
    mutation_pool=crossover_pool[:,1:]*mutation_rate
    final_mutation=np.column_stack((mutation_X,mutation_pool))
    return final_mutation

#mutation_pool=mutation(parents_pool)
#print(mutation_pool)
#print(mutation_pool)
#mutation_rate=random.uniform(0.98,1.02)
#X=mating_pool[:,0]
#mutation_pool=mating_pool[:,1:]*mutation_rate
#yui=np.column_stack((X,mutation_pool))
#print(mutation_pool,yui)

In [ ]:
#survival selection by def
def survivor_selection():
    new_mating_pool=np.insert(mutation(crossover_process(parent_selection(mating_pool))),0,mating_pool,axis=0)
    fitness_new_pool=fitness(new_mating_pool)
    mix_new_fitness=np.column_stack((new_mating_pool,fitness_new_pool))

    mixsortnew=mix_new_fitness[mix_new_fitness[:, 5].argsort()]
    mixsortnew =mixsortnew[::-1]
    mixsortnew=mixsortnew[:]
    new_mating_pool=mixsortnew[0:30,0:5]
    return new_mating_pool
    #return fitness(new_mating_pool)


test2=survivor_selection()
print(test2)

[[1.00000000e+00 6.93259146e+01 5.56673321e-01 3.44334013e+00
  8.60835032e+02]
 [2.00000000e+00 7.33431447e+01 4.87806518e-01 8.60835032e-01
  7.46057028e+02]
 [2.00000000e+00 7.31000000e+01 4.15000000e-01 1.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 5.14205459e+01 4.36156416e-01 1.14778004e+00
  1.03300204e+03]
 [2.00000000e+00 6.78500000e+01 3.15000000e-01 3.00000000e+00
  9.50000000e+02]
 [2.00000000e+00 8.39027211e+01 5.05023219e-01 1.14778004e+00
  6.88668026e+02]
 [2.00000000e+00 7.78768759e+01 4.76328718e-01 3.44334013e+00
  1.09039104e+03]
 [1.00000000e+00 6.60500000e+01 4.85000000e-01 3.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 6.04000000e+01 3.80000000e-01 3.00000000e+00
  7.50000000e+02]
 [2.00000000e+00 4.48000000e+01 4.25000000e-01 1.00000000e+00
  9.00000000e+02]
 [2.00000000e+00 6.39000000e+01 4.40000000e-01 7.50000000e-01
  6.50000000e+02]
 [2.00000000e+00 7.41000000e+01 3.75000000e-01 3.00000000e+00
  9.50000000e+02]
 [2.00000000e+00 7.58108718e+01 3.615507

In [ ]:
def genetic_algorithm():
    parents=parent_selection(mating_pool)
    
    
    cross_p=crossover_process(parents)
   
    mutant_p=mutation(cross_p)
    survived_p=survivor_selection()
    return survived_p
    


print(genetic_algorithm())


[[1.00000000e+00 8.21542207e+01 3.91802869e-01 3.73145590e+00
  1.18162770e+03]
 [2.00000000e+00 7.31000000e+01 4.15000000e-01 1.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 9.09231420e+01 5.47280198e-01 9.32863974e-01
  8.08482111e+02]
 [2.00000000e+00 7.51266454e+01 6.03252037e-01 3.73145590e+00
  7.46291179e+02]
 [2.00000000e+00 8.43930942e+01 5.16184732e-01 1.24381863e+00
  7.46291179e+02]
 [2.00000000e+00 6.78500000e+01 3.15000000e-01 3.00000000e+00
  9.50000000e+02]
 [1.00000000e+00 6.60500000e+01 4.85000000e-01 3.00000000e+00
  6.00000000e+02]
 [2.00000000e+00 6.04000000e+01 3.80000000e-01 3.00000000e+00
  7.50000000e+02]
 [2.00000000e+00 4.48000000e+01 4.25000000e-01 1.00000000e+00
  9.00000000e+02]
 [2.00000000e+00 6.39000000e+01 4.40000000e-01 7.50000000e-01
  6.50000000e+02]
 [2.00000000e+00 7.94800106e+01 5.28622919e-01 1.24381863e+00
  1.11943677e+03]
 [2.00000000e+00 7.41000000e+01 3.75000000e-01 3.00000000e+00
  9.50000000e+02]
 [2.00000000e+00 5.57230747e+01 4.726510

In [ ]:
initial_gen=0
max_gen=1000

import numpy as np


while initial_gen<max_gen:
   x_new=genetic_algorithm()
   initial_gen+=1 
   mating_pool=x_new
   
   first=x_new[0]
   first=np.asarray(first)
   print([first])
   print("gen",initial_gen,"=",x_new)
   
   test=new_model.predict(x_new)
   c2test=test[:,2]+test[:,4]+test[:,3]
   print("best results:",test[0])
   
   print("Fittest C2H4+ethanol:",c2test[0])
   print(c2test[0])
   if c2test[0]>=80 : break
   #elif np.sum(test[0])>=97.5: break
   

Streaming output truncated to the last 5000 lines.
  7.92049621e+02]
 [1.00000000e+00 7.27018693e+01 4.26511120e-01 3.56581089e+00
  7.94972010e+02]
 [1.00000000e+00 7.44648112e+01 4.27564097e-01 3.55073606e+00
  7.91611184e+02]
 [1.00000000e+00 7.51819688e+01 4.26819659e-01 3.55950216e+00
  7.85217126e+02]
 [1.00000000e+00 7.25855206e+01 4.26879843e-01 3.54505362e+00
  7.90344326e+02]
 [1.00000000e+00 7.30105289e+01 4.28321895e-01 3.56877584e+00
  7.95633023e+02]
 [1.00000000e+00 7.27834143e+01 4.27615587e-01 3.55993083e+00
  7.95863678e+02]
 [1.00000000e+00 7.44521951e+01 4.27491657e-01 3.55889910e+00
  7.85084091e+02]
 [1.00000000e+00 7.29981591e+01 4.28249327e-01 3.56520676e+00
  7.94837322e+02]
 [1.00000000e+00 7.26895519e+01 4.26438859e-01 3.55013448e+00
  7.91477066e+02]
 [1.00000000e+00 7.30712366e+01 4.28678042e-01 3.55368847e+00
  7.92269403e+02]
 [1.00000000e+00 7.30588566e+01 4.28605413e-01 3.56817120e+00
  7.95498224e+02]
 [1.00000000e+00 7.51067804e+01 4.26392803e-01 3.54

In [ ]:
print(test[0],mating_pool[0])
print(new_model.predict(mating_pool))


[17.9887295  17.90061808 40.1230201   2.92599917 18.78715483] [1.00000000e+00 7.41993980e+01 4.26539651e-01 3.54681511e+00
 7.82418394e+02]
[[17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.92599917 18.78715483]
 [17.9887295  17.90061808 40.1230201   2.